# Generated by Django 3.2.7 on 2022-10-17 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cagtegory',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
    ]
