# Generated by Django 3.2.7 on 2022-11-01 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20221020_0948'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartOrderItems',
            new_name='CartOrderProducts',
        ),
        migrations.AlterField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='core.product'),
        ),
    ]
