# Generated by Django 3.2.7 on 2022-11-06 23:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_auto_20221106_2355'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='wishlist',
            new_name='wishlist_model',
        ),
    ]
