# Generated by Django 3.2.7 on 2022-11-16 18:51

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_wishlist_wishlist_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='pid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', blank=True, length=10, max_length=20, null=True, prefix='SKU'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='paid_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
