# Generated by Django 3.2.7 on 2022-11-16 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20221116_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorder',
            old_name='pid',
            new_name='sku',
        ),
    ]
